language: node_js

node_js:
   - node
   
-branches:		
   only:		
      - master # will only build for master branch commits

before_script:
   - npm install -g --silent firebase-tools # installs firebase to run firebase deploy
   - npm install -g --silent @angular/cli

script:
   - ng build --prod
   - ls

after_success:
  - firebase use cacciaaltesoroprod && firebase deploy --only hosting --token $FIREBASE_TOKEN --non-interactive # firebase deploy after angular-cli build


notifications:
    on_success: always # default: change
    on_failure: never # default: always
